### ISSUE TITLE
Adding option in settings menu to edit the log path. 

### ISSUE THREAD

**Issue by Daniel-Donegan** [setup-your-mac/SYM-Helper#23]
**Is your feature request related to a problem? Please describe.**
- Right now, it is a little bit tedious to change every time after a new script generates.

**Describe the solution you'd like**
- Ideally, having an option in the left panel of the settings menu called 'Log Path' or something like that could be nice. An option within there to enter a file path would be ideal.

**Comment by dan-snelson** [comment]
Greetings, @Daniel-Donegan.

Currently, [`scriptLog`](https://github.com/setup-your-mac/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L49) is Parameter `4`, so in your Jamf Pro policy, you can specify the path once.

(See: [4. Implementation](https://snelson.us/2024/02/setup-your-mac-1-14-0-under-the-hood/#4) > Create a Jamf Pro Policy to Setup Your Mac > Step No. 2.)
