### ISSUE TITLE
Feature Request: Local Validation `listitem` and `icon` GUI fields

### ISSUE THREAD

**Issue by dan-snelson** [setup-your-mac/SYM-Helper#6]
Leslie:

Thanks again for all your efforts to release SYM-Helper.

**Two words:** Game. Changer.

---

With SYM-Helper `0.7.7 (20230919-91A)`, after adding a **Validation**, the GUI allows the `progresstext` to be populated, but there isn't a way to populate `listitem` or `icon`.

<img width="1027" alt="Screenshot 2023-09-20 at 10 18 07 AM" src="https://github.com/BIG-RAT/SYM-Helper/assets/24623109/302c9104-9cda-4a2d-bd5f-6ffdd2cf9974">

JSON output:

```
{
    "listitem": "",
    "icon": "",
    "progresstext": "FileVault is built-in to macOS and provides full-disk encryption to help prevent unauthorized access to your Mac.",
    "trigger_list": [
                        {
                        "trigger": "filevault",
                        "validation": "Local"
                        }
    ]
}
```

**Comment by arnoldtaw** [comment]
Interested! If possible, requesting to add the icon preview as well? 

<img width="1027" alt="5 B 4 c" src="https://github.com/BIG-RAT/SYM-Helper/assets/2093094/20631c3c-ee32-4d30-b771-ef6d5bf73e79">

**Comment by BIG-RAT** [comment]
Text fields and icon preview should all be working now.
